name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  cs:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    name: Coding Style

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring
          tools: composer:v2
          coverage: none

      - name: Set COMPOSER_ROOT_VERSION
        run: echo "COMPOSER_ROOT_VERSION=0.3.99" >> $GITHUB_ENV

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Check Coding Style - PHP
        run: vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --diff --verbose

      - name: Check composer.json format
        run: |
          composer remove --no-interaction roundcube/roundcubemail
          composer validate --strict --no-check-lock && composer normalize --dry-run --no-check-lock

  phpstan:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    name: Static Analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring
          tools: composer:v2
          coverage: none

      - name: Set COMPOSER_ROOT_VERSION
        run: echo "COMPOSER_ROOT_VERSION=0.3.99" >> $GITHUB_ENV

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run Static Analysis
        run: vendor/bin/phpstan analyse

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: false
      matrix:
        php: ["7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]

    name: Test / PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          tools: composer:v2
          coverage: none

      - name: Set COMPOSER_ROOT_VERSION
        run: echo "COMPOSER_ROOT_VERSION=0.3.99" >> $GITHUB_ENV

      - name: Test - install plugin
        run: |
          cd test-composer
          composer install --prefer-dist --no-interaction --no-progress

      - name: Test - verify install
        run: |
          cd test-composer
          ls -lah vendor/roundcube/roundcubemail/plugins/carddav
          ls -lah vendor/roundcube/roundcubemail/plugins/carddav/config.inc.php
